name : null 
channels :
   - nvidia
   - rapidsai
   - conda-forge
dependencies :
  - python=3.9
  - pytorch-lightning
  - rapids=22.12
  - tensorflow
  - jax
  - git
  - jupyterlab
  - jupyterlab-nvdashboard
  - dask-labextension
  - lightgbm