name : null
channels :
   - conda-forge
dependencies :
  - python
  - dask
  - tensorflow
  - jax
  - git
  - jupyterlab
  - dask-labextension
  - umap-learn
  - wandb
  - lightgbm
  - gh
  - holoviews
  - hvplot
  - graphistry
  - pycaret
  - ray-tune
  - dask-jobqueue
  - ca-certificates
  - certifi
  - openssl
  - nodejs
  - graphviz
  - ipyparallel
  - code-server==4.9.1
  - pip
  - pip:
    - -r requirements.txt